### ISSUE TITLE
getting top related movies

### ISSUE THREAD

**Issue by kelemul** [ririw/ririw.github.io#3]
I am just new to recommendation system. is there a way of getting  top similar movies for a specific movie?

**Comment by ririw** [comment]
The easiest way would be to maybe take the trained NN and optimise the "movie" input to maximize the star rating, then find movies most similar.

Recall that the movie is returned by an embedding layer in Keras. You could freeze the nn weights and remove the embedding layer, and feed in a vector of length 32 in its place. Then, you could optimise the vector's value to maximise the `result` rating. The `user` vector is constant throughout and is whomever you're recommending to.

Then, once that's all done, find the set of movies most similar to the vector you found with k nearest neighbors. 

One important point - check that the results you find are actually good recommendations. There's nothing that forces the network to make "closeness" a meaningful metric, so just check that the movies similar to the one you found are actually good.

Finally, an interesting extension to this would be to explore the concept of distance a little bit. There are two areas to explore:
 - Which distance metric you use.
 - And whether you can weight the 32 items in the vector for better performance.

Another important thing to consider - how can you deal with multi-modal distributions? After all, my *favorite* movies might be action, but maybe my second favorite are dark comedies. The approach above would only find a single local minimum, where we want many local minima representing the different genres.

Sorry for my late reply btw, I hope this is helpful!

**Comment by kelemul** [comment]
thank you! found it important.
